name: unit tests
on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pipenv'
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Environment
        run: pipenv install --dev
      - name: Run Unit Tests
        run: pipenv run unittest
